DOCKER=docker
DOCKER_PREFIX=jam

DOCKER_IMG_NAME=jyvert
DOCKER_BUILDER_IMG_NAME=graal

DOCKER_BUILD_VERSION=latest
DOCKER_BUILDER_VERSION=latest

DOCKER_NAME = $(DOCKER_PREFIX)/$(DOCKER_IMG_NAME):$(DOCKER_BUILD_VERSION)
DOCKER_BUILDER_NAME = $(DOCKER_PREFIX)/$(DOCKER_BUILDER_IMG_NAME):$(DOCKER_BUILDER_VERSION)

DOCKER_BUILD_DIR=.
DOCKER_BUILDER_DIR=./docker-builder

DOCKER_BUILD_CMD=$(DOCKER) build -t $(DOCKER_NAME) $(DOCKER_BUILD_DIR)
DOCKER_BUILDER_CMD=$(DOCKER) build -t $(DOCKER_BUILDER_NAME) $(DOCKER_BUILDER_DIR)
DOCKER_CREATE_CMD=$(DOCKER) create $(DOCKER_NAME)

OUTPUT_FILE=app-standalone
OUTPUT_DIRECTORY=target/
OUTPUT=$(OUTPUT_DIRECTORY)$(OUTPUT_FILE)

.PHONY: clean build build-base

all: $(OUTPUT)

clean:
	rm -f $(OUTPUT)

build-base:
	$(DOCKER_BUILDER_CMD)

build: build-base
	$(DOCKER_BUILD_CMD)

$(OUTPUT): build
	CID=$$($(DOCKER_CREATE_CMD)) ;\
	$(DOCKER) cp $$CID:/$(OUTPUT_FILE) $(OUTPUT) ;\
	$(DOCKER) rm $$CID
